# Generated by Django 4.1.7 on 2023-03-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezone', '0006_alter_productreview_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
